### ISSUE TITLE
How can I get 3D full body key points?

### ISSUE THREAD

**Issue by LittleGrapelet** [openxrlab/xrmocap#100]
Hi, thanks for your work! How can I generate multi-view multi-person full body keypoints3d?  Thank very much.

**Comment by yl-1993** [comment]
Hi @LittleGrapelet , to have a quick start, you may follow the [inference tutorials](https://github.com/openxrlab/xrmocap/blob/main/docs/en/getting_started.md#inference) to generate keypoints3d and SMPL(-X).

As the repo provides several methods to choose from, it depends on your specific need for obtaining keypoints3d, e.g., whether to apply tracking or whether to use learning-based approach.

**Comment by yl-1993** [comment]
Closed as it has been incative for a while. Feel free to re-open it if the problem is not solved.
