### ISSUE TITLE
SMPLXDData displacement shape error

### ISSUE THREAD

**Issue by dongyang-mt** [openxrlab/xrmocap#109]
displacement shape is [batch_size, N_VERTS, 3] is fine at [xrmocap/model/registrant/smplifyxd.py#L36](https://github.com/openxrlab/xrmocap/blob/2fc432ed5e144bd7dd76e613b260229458adc379/xrmocap/model/registrant/smplifyxd.py#L36).
but define error shape [batch_size, NUM_VERTS] at [xrmocap/data_structure/body_model/smplxd_data.py#L55](https://github.com/openxrlab/xrmocap/blob/2fc432ed5e144bd7dd76e613b260229458adc379/xrmocap/data_structure/body_model/smplxd_data.py#L55)

**Comment by LazyBusyYang** [comment]
This issue is fixed in https://github.com/openxrlab/xrmocap/pull/112.
