### ISSUE TITLE
Can you provide a tutorial on handling customer data？

### ISSUE THREAD

**Issue by Dian-Yi** [openxrlab/xrmocap#118]
Thanks for your work, Can you provide a tutorial on customer data？

**Comment by LazyBusyYang** [comment]
Thank you for your attention to XRMoCap! May I ask specifically which method you would like to apply on customed data? We will provide assistance based on the different methods.

**Comment by LazyBusyYang** [comment]
Now we're working on it in https://github.com/openxrlab/xrmocap/pull/123.

**Comment by LazyBusyYang** [comment]
The required tutorial is now available [here](https://github.com/openxrlab/xrmocap/blob/main/docs/en/tools/run_mview_sperson_estimator.md). Feel free to re-open it if the problem is not solved.
