### ISSUE TITLE
API for Panoptic dataset

### ISSUE THREAD

**Issue by 3huo** [openxrlab/xrmocap#121]
Hi, I want to test xrmocap on CMU Panoptic format data. Is there any api for that? Or can u give me some advice for that?

**Comment by LazyBusyYang** [comment]
Hello!
1. During the data preparation stage, if you want to convert Panoptic data to a format that can be used by XRLab, please refer to the [dataset preparation document](https://github.com/openxrlab/xrmocap/blob/main/docs/en/tools/prepare_dataset.md). 
2. In the data_converter, you need to select a configuration file. If you are using a TopDown method like MVPose, you can refer to this [configuration file](https://github.com/openxrlab/xrmocap/blob/main/configs/mvpose/panoptic_config/panoptic_data_converter_testset.py).
3. Regarding the specific functions and parameters of the data_converter, you can refer to the [docstring](https://github.com/openxrlab/xrmocap/blob/main/xrmocap/data/data_converter/panoptic_data_converter.py#L40).
