### ISSUE TITLE
Surpport batch_size>1?

### ISSUE THREAD

**Issue by Dragon2938734** [openxrlab/xrmocap#124]
excusme, does this code surpport batch_size>1? for example, in position_encoding.py code:
       pixel_camera = torch.bmm(xy1.flatten(1, 2).repeat(views, 1, 1),   torch.inverse(K).transpose(2, 1))
will get error if  batch_size>1, because the dim 0  do not equal. Should i replace ".repeat(views, 1, 1)"  to "" .repeat(batch*views, 1, 1)"?

**Comment by wqyin** [comment]
Sorry, currently we only support `batch_size = 1`. MVP processes all the views for each frame at a time. Please feel free to modify the network to fit your use case better.
