### ISSUE TITLE
2D keypoints Detection

### ISSUE THREAD

**Issue by 3huo** [openxrlab/xrmocap#128]
When I use the defalt 2d keypoints detector i.e. [mmpose_hrnet_w48_coco_wholebody_384x288_dark_plus.py](https://github.com/openxrlab/xrmocap/blob/main/configs/modules/human_perception/mmpose_hrnet_w48_coco_wholebody_384x288_dark_plus.py)
I get a wrong 2d keypoint result about the big_toe and small_toe points. 
I wonder if it is the kpts detector's fault or some other resons?

**Comment by LazyBusyYang** [comment]
Yes, I have also encountered the same issue during the use of XRMoCap. It may be possible to solve this problem by replacing the MMPose model with another one, but I have not tried yet.    
Also, accepting incorrect 2D detection results is OK. Adjusting the SMPLify parameters can reduce the impact of incorrect toe positions. For SMPLify(X) parameters, please ask @wqyin.
