### ISSUE TITLE
import utils requires torch

### ISSUE THREAD

**Issue by LazyBusyYang** [openxrlab/xrmocap#131]
https://github.com/openxrlab/xrmocap/blame/8b4931d071f3484d77842f4265cc2b000f9916ff/xrmocap/utils/__init__.py#L2
When I call `from xrmocap.utils.xxx_utils import xxx`, I get `ModuleNotFoundError: No module named 'torch'`.

**Comment by jiaqiAA** [comment]
We have solved this problem.
