### ISSUE TITLE
Can I adjust the number of camera views for mvp model?

### ISSUE THREAD

**Issue by jiku100** [openxrlab/xrmocap#143]
This repository provides configs with 3 and 5 views for panoptic datasets. If I want to use 1, 2, or 4 views, can I just change the number of cameras in the config file? In this case, can I just use the weight file given?

**Comment by DizzyBusyTing** [comment]
For view selection, please modify the list [here](https://github.com/openxrlab/xrmocap/blob/main/configs/modules/data/data_converter/panoptic_data_converter_trainset_wo_perception.py#L12).   
For the weight file, you can have a try with the given one, but it is recommended to train a new weight as the views have not been seen before.

**Comment by LazyBusyYang** [comment]
For view selection, please modify the list [here](https://github.com/openxrlab/xrmocap/blob/main/configs/modules/data/data_converter/panoptic_data_converter_trainset_wo_perception.py#L12) and run data converter.   
For weight file, you can have a try but it is recommended to train a new one as the views have not been seen by the old weight.
