### ISSUE TITLE
Reprodution for 4D association graph

### ISSUE THREAD

**Issue by aichunling0418** [openxrlab/xrmocap#31]

**Comment by aichunling0418** [comment]
https://confluence.sensetime.com/display/openverse/XRMoCap+Benchmark+0.6.0

**Comment by KHao123** [comment]
- [x] 根据杨哥和佳琦的comments重构代码

- [x] 支持多种骨架格式（fourdag19，openpose25，coco）作为输入

- [x] 支持多个数据集

- [ ] 对各种数据集和骨架格式调参和debug

**Comment by KHao123** [comment]
- [x]  Refactor code according to comments of GaoYang and JiaQi.
- [ ] add unit test to improve coverage 
- [ ] algin and add benchmark

**Comment by KHao123** [comment]
merge to main branch
