### ISSUE TITLE
How to test the model on the custom image ?

### ISSUE THREAD

**Issue by Taylorminer** [openxrlab/xrmocap#53]
Thanks for your work ! I want to test the model on my own data.  So,how to test the model on the custom image ?

**Comment by yl-1993** [comment]
Hi @Taylorminer , you may refer to [inference](https://github.com/openxrlab/xrmocap/blob/main/docs/en/getting_started.md#inference) to try the example and prepare the data similar to [Shelf_50](https://openxrlab-share-mainland.oss-cn-hangzhou.aliyuncs.com/xrmocap/example_resources/Shelf_50.zip).

**Comment by Taylorminer** [comment]
> Hi @Taylorminer , you may refer to [inference](https://github.com/openxrlab/xrmocap/blob/main/docs/en/getting_started.md#inference) to try the example and prepare the data similar to [Shelf_50](https://openxrlab-share-mainland.oss-cn-hangzhou.aliyuncs.com/xrmocap/example_resources/Shelf_50.zip).

Thanks for your reply .Will other program be changed (except the data file and the camera parameters) ?

**Comment by Taylorminer** [comment]
What's meaning od the following parameters ?
![image](https://user-images.githubusercontent.com/41726592/205042093-0f40cec4-7ce3-4cd8-a6fd-6266aaee68ac.png)

**Comment by Taylorminer** [comment]
What's meaning of the following parameters ?
![image](https://user-images.githubusercontent.com/41726592/205042093-0f40cec4-7ce3-4cd8-a6fd-6266aaee68ac.png)

**Comment by qinb** [comment]
I also have the same question, could you offer detailed guidance or procedure? thanks

**Comment by Taylorminer** [comment]
> I also have the same question, could you offer detailed guidance or procedure? thanks
Can you run Campus dataSet successfully ?

**Comment by LazyBusyYang** [comment]
> What's meaning of the following parameters ? ![image](https://user-images.githubusercontent.com/41726592/205042093-0f40cec4-7ce3-4cd8-a6fd-6266aaee68ac.png)

Those are the distortion coefficients of a fisheye camera model. For more details, please refer to [XRPrimer Cameras](https://github.com/openxrlab/xrprimer/blob/main/docs/en/data_structure/camera.md#fisheye)

**Comment by LazyBusyYang** [comment]
> Shelf_50

For custom data, please check our [unified definition of a dataset](https://github.com/openxrlab/xrmocap/blob/main/docs/en/tutorials/new_dataset.md#file-tree-of-our-unified-format). As long as your data matches the definition, configuration file is the only thing you have to change.

**Comment by Taylorminer** [comment]
Thanks for your reply!
