### ISSUE TITLE
How can I visualize the 3d data in a world coordinate system?

### ISSUE THREAD

**Issue by Taylorminer** [openxrlab/xrmocap#55]
Thanks for your work! How can I visualize the 3d data in a world coordinate system? like this:
![image](https://user-images.githubusercontent.com/41726592/205040625-fefbab98-38f7-421e-80aa-6e23d82454c9.png)

**Comment by LazyBusyYang** [comment]
Sorry, we do not support real-scale kps3d visualization for the moment. If you try to add  `value_range=None` at this [position](https://github.com/openxrlab/xrmocap/blob/main/xrmocap/core/visualization/visualize_keypoints3d.py#L176), it may help, according to my memory.   
A new keypoints visualization system is comming in XRPrimer. When it's done, I will update the API link here.

**Comment by Taylorminer** [comment]
> Sorry, we do not support real-scale kps3d visualization for the moment. If you try to add `value_range=None` at this [position](https://github.com/openxrlab/xrmocap/blob/main/xrmocap/core/visualization/visualize_keypoints3d.py#L176), it may help, according to my memory. A new keypoints visualization system is coming in XRPrimer. When it's done, I will update the API link here.

Thanks for your reply! I will try.

**Comment by LazyBusyYang** [comment]
Hi @Taylorminer ! I am glad to tell you that we have provided the visualization tool you need in [xrprimer v0.7.0](https://github.com/openxrlab/xrprimer/releases/tag/v0.7.0). There is no need to modify the code, just install xrprimer by `pip install xrprimer==0.7.0`. It can directly take a Keypoints instance as input, draw keypoints in the coordinate system, and display coordinate axis values in the image.
Sorry for the delay in publishing this feature, and currently there is no readme in markdown format, but we have provided a relatively complete [docstring ](https://github.com/openxrlab/xrprimer/blob/main/python/xrprimer/visualization/keypoints/visualize_keypoints3d.py#L29)in the code.

**Comment by Taylorminer** [comment]
@LazyBusyYang Thanks for your work !  I want to test the model in a custom scene. The first step is to calibrate the cameras. I noticed that [xrprimer](https://github.com/openxrlab/xrprimer/releases/tag/v0.7.0) support this function. But how to use it ? The [instruction](https://github.com/openxrlab/xrprimer/blob/main/docs/en/tools/calibrate_multiple_cameras.md ) is null.
