### ISSUE TITLE
Run demo failed.

### ISSUE THREAD

**Issue by Yamato-01** [openxrlab/xrmocap#81]
Multiple People demo:
`python tools/mview_mperson_topdown_estimator.py \
      --estimator_config 'configs/mvpose_tracking/mview_mperson_topdown_estimator.py' \
      --image_and_camera_param 'xrmocap_data/Shelf_50/image_and_camera_param.txt' \
      --start_frame 300 \
      --end_frame 350 \
      --output_dir 'output/estimation' \
      --enable_log_file`
error:
`- ERROR - use_shoulder_hip_only is deprecated, please manually set: body_weight=0.0, face_weight=0.0, hand_weight=0.0, shoulder_weight=1.0, hip_weight=1.0 to make sure correct weights are set.`

**Comment by jiaqiAA** [comment]
HI, we've fixed it.
