### ISSUE TITLE
how to run /tools/e2e with bottom_up 4DAG

### ISSUE THREAD

**Issue by YaoBeiji** [openxrlab/xrmocap#93]
Could you provide an example of this Python command?

**Comment by KHao123** [comment]
You can call 4DAG in the way similar to mvpose:
`python tools/mview_mperson_evaluation.py 
      --enable_log_file 
      --evaluation_config configs/fourdag/shelf_config/eval_keypoints3d.py
`

**Comment by KHao123** [comment]
This issue was closed because it has been inactive for 7 days since being marked as stale. Feel free to re-open it if the problem is not solved.
