### ISSUE TITLE
[Feature Request] Support Human3.6M dataset

### ISSUE THREAD

**Issue by BingliangLi** [openxrlab/xrmocap#97]
Please consider adding Human3.6M support as many paper used it for evaluation.

link: http://vision.imar.ro/human3.6m/description.php

**Comment by LazyBusyYang** [comment]
Thank you for your suggestion! Considering the low importance of the Human3.6M dataset in multiple [benchmarks](https://github.com/openxrlab/xrmocap/blob/main/docs/en/benchmark.md) that we have published, we currently do not support this dataset. If you have an urgent need for it, you can convert the Human3.6M dataset to our supported format according to the [new dataset documentation](https://github.com/openxrlab/xrmocap/blob/main/docs/en/tutorials/new_dataset.md), or write your wish in the [wishlist](https://github.com/openxrlab/xrmocap/discussions/9). We will consider addressing the most popular wishes at an appropriate time.
