### ISSUE TITLE
Can you open the tools to make smc file ? 

### ISSUE THREAD

**Issue by Frizy-up** [openxrlab/xrmocap#98]
Can you open the tools to make custom mview smc file ?

**Comment by LazyBusyYang** [comment]
Sorry, creating SMC files involves complex third-party dependencies such as Kinect SDK, hardware synchronization, and video encoding, and belongs to the data collection toolchain according to its function, which is currently not included in the open-source plan of this project.
You can explain your needs for using XRMoCap on the issue page. If your need is to run a tool with the same functionality as process_smc on data you have collected yourself, you can consider directly calling the API of the [MultiViewSinglePersonSMPLEstimator](https://github.com/openxrlab/xrmocap/blob/main/xrmocap/core/estimation/mview_sperson_smpl_estimator.py) according to the documentation.

**Comment by LazyBusyYang** [comment]
This issue was closed because it has been inactive for 7 days since being marked as stale. Feel free to re-open it if the problem is not solved.
